"use client";
import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Award, Flag, Heart, RefreshCcw, Star, XCircle } from "lucide-react";
import Link from "next/link";
import type { ActivityResult, AttemptRecord, Mission } from "@/lib/learning/types";
import { ActivityRenderer } from "@/components/activities/activity-renderer";
import { MissionComplete } from "@/components/learning/mission-complete";
import { UnitComplete } from "@/components/learning/unit-complete";
import { finalizeUnit6Completion, readMissionResume, readPilotProgress, readUnit6Completion, saveMissionResume, savePilotProgress, type SavedActivityProgress, type SavedUnitCompletion } from "@/lib/learning/pilot-progress";
import { unit6Missions } from "@/lib/learning/unit-6";
import { completeRemoteMission, loadRemoteMissionResume, loadRemoteUnitCompletion, saveRemoteActivity, saveRemoteActivityDraft, startRemoteMission } from "@/lib/learning/progress-repository";

export function MissionEngine({ mission, nextMissionTitle }: { mission: Mission; nextMissionTitle?: string }) {
  const [briefing,setBriefing]=useState(mission.activities.length>0); const [activityIndex,setActivityIndex]=useState(0); const [lives,setLives]=useState(3); const [attempts,setAttempts]=useState<AttemptRecord[]>([]); const [feedback,setFeedback]=useState<"correct"|"wrong"|null>(null); const [finished,setFinished]=useState(false); const [failed,setFailed]=useState(false); const [savedActivities,setSavedActivities]=useState<Record<string,SavedActivityProgress>>({}); const [resumed,setResumed]=useState(false); const [completedScore,setCompletedScore]=useState<number|null>(null); const [unitCompletion,setUnitCompletion]=useState<SavedUnitCompletion|null>(null);
  const activity=mission.activities[activityIndex]; const accuracy=useMemo(()=>attempts.length?Math.round(attempts.filter((item)=>item.correct).length/attempts.length*100):100,[attempts]);
  useEffect(()=>{let active=true;(async()=>{await startRemoteMission(mission.id);const remote=await loadRemoteMissionResume(mission.id);const saved=remote??readMissionResume(mission.id);if(!active||!saved)return;saveMissionResume(saved);setSavedActivities(saved.activities);setAttempts(saved.attempts??[]);setLives(saved.livesRemaining??3);if(saved.status==="COMPLETED"){const legacy=readPilotProgress().find((item)=>item.missionId===mission.id);setCompletedScore(saved.finalScore??legacy?.score??100);if(mission.order===25)setUnitCompletion(await loadRemoteUnitCompletion("unit-6")??readUnit6Completion()??finalizeUnit6Completion(unit6Missions));setBriefing(false);setFinished(true)}else if(saved.status==="IN_PROGRESS"){const firstOpen=mission.activities.findIndex((item)=>saved.activities[item.id]?.status!=="COMPLETED");setActivityIndex(firstOpen<0?Math.min(saved.currentActivityIndex,mission.activities.length-1):firstOpen);setFailed(saved.livesRemaining===0);setBriefing(false);setResumed(true)}})();return()=>{active=false}},[mission.activities,mission.id,mission.order]);
  function persist(status:"IN_PROGRESS"|"COMPLETED",index:number,activities=savedActivities,remainingLives=lives,attemptHistory=attempts){saveMissionResume({missionId:mission.id,status,currentActivityIndex:index,activities,attempts:attemptHistory,updatedAt:new Date().toISOString(),livesRemaining:remainingLives})}
  async function handleAnswer(result:ActivityResult){if(feedback==="correct")return;const nextLives=result.correct?lives:Math.max(0,lives-1);const record:AttemptRecord={activityId:activity.id,attemptNumber:attempts.filter((item)=>item.activityId===activity.id).length+1,score:result.score,livesRemaining:nextLives,response:result.response,correct:result.correct};const nextAttempts=[...attempts,record];const progress={...savedActivities,[activity.id]:{status:result.correct?"COMPLETED" as const:"IN_PROGRESS" as const,answer:result.response,score:result.score}};setSavedActivities(progress);persist("IN_PROGRESS",activityIndex,progress,nextLives,nextAttempts);setAttempts(nextAttempts);setLives(nextLives);setFeedback(activity.type==="matching"&&!result.correct?null:result.correct?"correct":"wrong");await saveRemoteActivity({activityKey:activity.id,response:result.response,score:result.score,correct:result.correct,livesRemaining:nextLives,attemptNumber:record.attemptNumber});if(!result.correct&&nextLives===0)setTimeout(()=>setFailed(true),700)}
  function continueJourney(){const wasCorrect=feedback==="correct";setFeedback(null);if(!wasCorrect)return;if(activityIndex===mission.activities.length-1){setFinished(true);saveProgress()}else{const next=activityIndex+1;setActivityIndex(next);persist("IN_PROGRESS",next)}}
  async function saveProgress(){const completedAt=new Date().toISOString();const remote=await completeRemoteMission(mission.id);const finalScore=remote?.score==null?accuracy:Number(remote.score);const earnedXp=remote?.xp_earned??mission.xpReward;setCompletedScore(finalScore);saveMissionResume({missionId:mission.id,status:"COMPLETED",currentActivityIndex:mission.activities.length,activities:savedActivities,attempts,updatedAt:completedAt,livesRemaining:lives,finalScore,xpEarned:earnedXp,completedAt});savePilotProgress({missionId:mission.id,status:"completed",score:finalScore,xpEarned:earnedXp,completedAt});if(mission.order===25)setUnitCompletion(await loadRemoteUnitCompletion("unit-6")??finalizeUnit6Completion(unit6Missions));}
  function restart(){const firstIncomplete=mission.activities.findIndex((item)=>savedActivities[item.id]?.status!=="COMPLETED");const resumeIndex=firstIncomplete<0?Math.min(activityIndex,mission.activities.length-1):firstIncomplete;setActivityIndex(resumeIndex);setLives(3);setFeedback(null);setFailed(false);setResumed(true);persist("IN_PROGRESS",resumeIndex,savedActivities,3,attempts)}
  if(!activity)return <section className="mx-auto max-w-xl rounded-[2rem] bg-white p-8 text-center shadow-xl"><h1 className="font-adventure text-3xl font-semibold">Mission route prepared</h1><p className="mt-3 font-medium text-[#62708a]">Activities for this checkpoint will be added in the next content sprint.</p></section>;
  if(finished&&mission.order===25&&unitCompletion)return <UnitComplete completion={unitCompletion}/>;
  if(finished)return <MissionComplete mission={mission} accuracy={completedScore??accuracy} nextMissionTitle={nextMissionTitle} activityResults={mission.activities.map((item)=>savedActivities[item.id]?.score??100)} activityResponses={Object.fromEntries(mission.activities.map(item=>[item.id,savedActivities[item.id]?.answer]))}/>;
  if(briefing)return <section className="mx-auto max-w-2xl rounded-[2rem] border border-[#dce5f2] bg-white p-7 text-center shadow-[0_22px_65px_rgba(13,48,91,.1)] sm:p-10"><div className="mx-auto grid size-16 place-items-center rounded-2xl bg-blue-50 text-[#125cdb]"><Flag size={32}/></div><p className="mt-5 text-xs font-black uppercase tracking-[.18em] text-[#125cdb]">Mission brief</p><h2 className="font-adventure mt-2 text-3xl font-semibold text-[#10233f]">{mission.title}</h2><p className="mx-auto mt-4 max-w-xl text-lg font-medium leading-8 text-[#62708a]">{mission.description}</p><div className="mx-auto mt-6 flex max-w-md flex-wrap justify-center gap-3"><span className="inline-flex items-center gap-2 rounded-full bg-orange-100 px-4 py-2 font-bold text-[#a94505]"><Star size={18} fill="currentColor"/> +{mission.xpReward} XP</span><span className="inline-flex items-center gap-2 rounded-full bg-emerald-100 px-4 py-2 font-bold text-emerald-700"><Award size={18}/> {mission.badgeReward}</span></div><button onClick={()=>{setBriefing(false);persist("IN_PROGRESS",0,{})}} className="btn-primary mt-7">Begin Mission</button></section>;
  if(failed)return <section className="mx-auto max-w-xl rounded-[2rem] bg-white p-8 text-center shadow-xl"><XCircle className="mx-auto text-[#e34848]" size={52}/><h1 className="font-adventure mt-5 text-3xl font-semibold">The trail pauses here</h1><p className="mt-3 font-medium text-[#62708a]">You used all three lives. Your progress is saved.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><button onClick={restart} className="btn-primary"><RefreshCcw size={18}/> Try again</button><Link href={`/student/unit/${mission.unitId}`} className="rounded-xl border border-[#dce5f2] px-5 py-3 font-bold text-[#31445f]">Return to Unit World Map</Link></div></section>;
  return <div>{resumed&&<div className="mb-5 rounded-2xl border border-blue-200 bg-blue-50 p-4"><p className="font-bold text-[#15365d]">Mission progress</p><div className="mt-2 flex flex-wrap gap-3 text-sm font-semibold text-[#62708a]">{mission.activities.map((item,index)=><span key={item.id}>{savedActivities[item.id]?.status==="COMPLETED"?"✅":"⬜"} Activity {index+1}</span>)}</div></div>}<div className="mb-5 flex items-center justify-between"><div className="text-sm font-bold text-[#62708a]">Challenge {activityIndex+1} of {mission.activities.length}</div><div className="flex gap-1" aria-label={`${lives} lives remaining`}>{[0,1,2].map((index)=><Heart key={index} size={25} className={index<lives?"text-[#e34848]":"text-[#cbd4df]"} fill="currentColor"/>)}</div></div><div className="mb-7 h-3 overflow-hidden rounded-full bg-[#dce5f2]"><motion.div animate={{width:`${activityIndex/mission.activities.length*100}%`}} className="h-full rounded-full bg-gradient-to-r from-[#21a46b] to-[#62d49a]"/></div><AnimatePresence mode="wait"><motion.div key={activity.id} initial={{opacity:0,x:24}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-24}}><ActivityRenderer activity={activity} initialResponse={savedActivities[activity.id]?.answer} onProgress={(response)=>{const progress={...savedActivities,[activity.id]:{status:"IN_PROGRESS" as const,answer:response,score:savedActivities[activity.id]?.score??0}};setSavedActivities(progress);persist("IN_PROGRESS",activityIndex,progress);void saveRemoteActivityDraft(activity.id,response,lives)}} onAnswer={handleAnswer}/></motion.div></AnimatePresence>{feedback&&<motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className={`mt-5 flex flex-col items-start justify-between gap-4 rounded-2xl p-5 sm:flex-row sm:items-center ${feedback==="correct"?"bg-emerald-100 text-[#12603e]":"bg-orange-100 text-[#7c3d0a]"}`}><div><p className="font-adventure text-xl font-semibold">{feedback==="correct"?"Trail cleared!":"Almost—keep exploring!"}</p><p className="text-sm font-medium">{feedback==="correct"?"Your answer is correct.":`${lives} ${lives===1?"life":"lives"} remaining.`}</p></div>{lives>0&&<button onClick={continueJourney} className="focus-ring rounded-xl bg-white px-5 py-3 font-bold shadow-sm">{feedback==="correct"?"Continue":"Try again"}</button>}</motion.div>}</div>;
}
