"use client";
import { useState } from "react";
import { PencilLine } from "lucide-react";
import type { ActivityProps } from "@/components/activities/multiple-choice-activity";
import { Submit } from "@/components/activities/multiple-choice-activity";
import { ActivityShell } from "@/components/activities/activity-shell";
import { WritingReview } from "@/components/activities/writing-review";
import { analyzeWriting, createWritingRecord, type WritingAnalysis, type WritingIssue } from "@/lib/learning/writing-evaluator";

export function EvaluatedWritingActivity({activity,onAnswer,initialResponse,onProgress}:ActivityProps){
  const item=activity.items[0];const initial=typeof initialResponse==="string"?initialResponse:"";const [value,setValue]=useState(initial);const [analysis,setAnalysis]=useState<WritingAnalysis|null>(null);const [firstVersion,setFirstVersion]=useState<string|null>(null);const [history,setHistory]=useState<WritingIssue[]>([]);const minimum=item.minSentences??5;const maximum=item.maxSentences??6;const sentenceCount=value.split(/[.!?]+/).filter(sentence=>sentence.trim()).length;
  function update(next:string){setValue(next);setAnalysis(null);onProgress?.(next)}
  function review(){if(firstVersion===null)setFirstVersion(value);const result=analyzeWriting(value,{minSentences:minimum,maxSentences:maximum,requireSecondConditional:true,requiredElements:[{label:"your hero name",pattern:/\b(my hero name is|my superhero name is|i am called)\b/i,message:"My hero name is..."},{label:"a special ability",pattern:/\b(my (special )?(ability|power) is|i can)\b/i,message:"My special ability is..."},{label:"your hero's personality",pattern:/\b(brave|kind|creative|helpful|responsible|honest|friendly|curious|determined|smart)\b/i,message:"I am brave and creative."},{label:"how your hero helps people",pattern:/\b(help|helps|protect|protects|save|saves|support|supports|rescue|rescues)\b/i,message:"I help people by..."}]});setAnalysis(result);setHistory(current=>[...current,...result.issues])}
  function complete(){onAnswer({correct:true,score:100,response:createWritingRecord(firstVersion??value,history,value)})}
  return <ActivityShell eyebrow="My Hero Identity Card" instructions={activity.instructions}><div className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><p className="font-bold leading-7 text-[#15365d]">{item.prompt}</p>{item.sentenceStarters?.length?<div className="mt-4 flex flex-wrap gap-2">{item.sentenceStarters.map(starter=><span key={starter} className="rounded-full bg-white px-3 py-1.5 text-sm font-semibold text-[#125cdb] shadow-sm">{starter}</span>)}</div>:null}</div><label className="label mt-6" htmlFor="hero-identity-writing">Your hero profile</label><textarea id="hero-identity-writing" value={value} onChange={event=>update(event.target.value)} className="field min-h-56 resize-y py-4" placeholder="My hero name is Lightning Fox. My special ability is super speed..."/><div className="mt-2 flex flex-wrap justify-between gap-3 text-sm font-bold text-[#62708a]"><span>Write → receive feedback → revise → complete.</span><span className={sentenceCount>=minimum&&sentenceCount<=maximum?"text-emerald-700":sentenceCount>maximum?"text-red-600":""}>{sentenceCount} / {minimum}–{maximum} sentences</span></div><div className="mt-5 rounded-2xl border border-violet-200 bg-violet-50 p-4"><p className="flex items-center gap-2 font-bold text-[#3d2874]"><PencilLine size={18}/> Target language</p><p className="mt-1 text-sm font-semibold text-[#5f4b88]">Include <strong>If + past simple, ... would + base verb</strong>.</p></div>{analysis&&<WritingReview analysis={analysis}/>} {!analysis?.canComplete?<Submit disabled={sentenceCount<minimum} label={analysis?"Review again":"Review my writing"} onClick={review}/>:<Submit disabled={false} label="Save my hero identity" onClick={complete}/>}</ActivityShell>;
}
