"use client";
import { useState } from "react";
import type { ActivityProps } from "@/components/activities/multiple-choice-activity";
import { Submit } from "@/components/activities/multiple-choice-activity";
import { ActivityShell } from "@/components/activities/activity-shell";
import { WritingReview } from "@/components/activities/writing-review";
import { analyzeWriting, createWritingRecord, type WritingAnalysis, type WritingIssue } from "@/lib/learning/writing-evaluator";

export function GuidedAdviceActivity({activity,onAnswer,onProgress}:ActivityProps){const [answers,setAnswers]=useState<Record<string,string>>({});const [analysis,setAnalysis]=useState<WritingAnalysis|null>(null);const [first,setFirst]=useState<Record<string,string>|null>(null);const [history,setHistory]=useState<WritingIssue[]>([]);const ready=activity.items.every(item=>(answers[item.id]?.trim().split(/\s+/).length??0)>=4);function update(id:string,value:string){const next={...answers,[id]:value};setAnswers(next);setAnalysis(null);onProgress?.(next)}function review(){if(first===null)setFirst({...answers});const results=activity.items.map(item=>analyzeWriting(answers[item.id]??"",{minWords:4}));const issues=results.flatMap(result=>result.issues);const combined={issues,blockingIssues:issues.filter(issue=>issue.blocking),suggestions:issues.filter(issue=>!issue.blocking),canComplete:results.every(result=>result.canComplete),wordCount:results.reduce((sum,result)=>sum+result.wordCount,0),sentenceCount:results.reduce((sum,result)=>sum+result.sentenceCount,0)};setAnalysis(combined);setHistory(current=>[...current,...issues])}function complete(){onAnswer({correct:true,score:100,response:createWritingRecord(first??answers,history,answers)})}return <ActivityShell eyebrow="Give Advice" instructions={activity.instructions}><div className="grid gap-5">{activity.items.map((item,index)=><label key={item.id} className="rounded-2xl border border-[#dce5f2] p-4 font-semibold text-[#31445f]"><span>{index+1}. {item.prompt}</span><textarea value={answers[item.id]??""} onChange={event=>update(item.id,event.target.value)} className="field mt-3 min-h-24 resize-y py-3" placeholder="You should… / You can… / Ask… / Try…"/></label>)}</div><p className="mt-4 text-sm font-semibold text-[#62708a]">Your ideas are evaluated flexibly. Grammar, spelling, and complete sentences are reviewed before completion.</p>{analysis&&<WritingReview analysis={analysis}/>} {!analysis?.canComplete?<Submit disabled={!ready} label={analysis?"Review again":"Review my advice"} onClick={review}/>:<Submit disabled={false} label="Save my advice" onClick={complete}/>}</ActivityShell>}
