"use client";
import { useMemo, useState } from "react";
import { CheckCircle2 } from "lucide-react";
import type { ActivityProps } from "@/components/activities/multiple-choice-activity";
import { Submit } from "@/components/activities/multiple-choice-activity";
import { ActivityShell } from "@/components/activities/activity-shell";
import { shuffleOptions } from "@/lib/learning/shuffle";

export function MultiSelectActivity({activity,onAnswer,onProgress}:ActivityProps){const item=activity.items[0];const correct=Array.isArray(item.answer)?item.answer:[];const options=useMemo(()=>shuffleOptions(item.options??[],`${activity.id}:${item.id}`),[activity.id,item]);const [selected,setSelected]=useState<string[]>([]);const [checked,setChecked]=useState(false);const success=checked&&selected.length===correct.length&&selected.every(value=>correct.includes(value));function toggle(value:string){if(checked)return;const next=selected.includes(value)?selected.filter(item=>item!==value):selected.length<3?[...selected,value]:selected;setSelected(next);onProgress?.(next)}function submit(){const hits=selected.filter(value=>correct.includes(value)).length;const isCorrect=hits===correct.length&&selected.length===correct.length;setChecked(isCorrect);onAnswer({correct:isCorrect,score:Math.round(hits/correct.length*100),response:selected})}return <ActivityShell eyebrow="Survival Challenge" instructions={activity.instructions}><p className="rounded-2xl bg-blue-50 p-4 font-semibold text-[#15365d]">{item.prompt}</p><p className="mt-4 font-black text-[#125cdb]">{selected.length}/3 actions selected</p><div className="mt-3 grid gap-3">{options.map(option=><button type="button" key={option} onClick={()=>toggle(option)} className={`focus-ring flex items-center gap-3 rounded-2xl border-2 p-4 text-left font-semibold ${selected.includes(option)?"border-[#21a46b] bg-emerald-50":"border-[#dce5f2]"}`}><CheckCircle2 className={selected.includes(option)?"text-[#21a46b]":"text-slate-300"}/>{option}</button>)}</div>{success&&<p className="mt-5 rounded-2xl bg-emerald-100 p-4 font-bold text-emerald-700">✓ Survival plan complete! These actions help a new student feel prepared, safe, and welcome.</p>} {!checked&&<Submit disabled={selected.length!==3} label="Complete survival plan" onClick={submit}/>}</ActivityShell>}
