"use client";
import { useMemo, useState } from "react";
import { Building2, Check, MapPin } from "lucide-react";
import type { ActivityProps } from "@/components/activities/multiple-choice-activity";
import { Submit } from "@/components/activities/multiple-choice-activity";
import { ActivityShell } from "@/components/activities/activity-shell";
import { FoxMascot } from "@/components/student/FoxMascot";
import { shuffleOptions } from "@/lib/learning/shuffle";

export function SchoolBuilderActivity({activity,onAnswer,onProgress}:ActivityProps){const places=useMemo(()=>shuffleOptions(activity.items[0].options??[],activity.id),[activity]);const [selected,setSelected]=useState<string[]>([]);function toggle(place:string){const next=selected.includes(place)?selected.filter(value=>value!==place):selected.length<5?[...selected,place]:selected;setSelected(next);onProgress?.(next)}return <ActivityShell eyebrow="Build Your School" instructions={activity.instructions}><div className="relative mb-6 min-h-64 overflow-hidden rounded-3xl bg-gradient-to-b from-sky-200 via-emerald-100 to-emerald-300 p-5"><div className="absolute bottom-0 right-3 scale-[.42]"><FoxMascot/></div><div className="relative grid grid-cols-2 gap-3 pr-24 sm:grid-cols-3">{selected.map((place,index)=><div key={place} className="rounded-2xl border-2 border-white bg-white/90 p-3 text-center shadow-lg"><Building2 className="mx-auto text-[#125cdb]"/><p className="mt-1 text-sm font-extrabold text-[#15365d]">{place}</p><span className="text-xs font-bold text-emerald-700">Campus zone {index+1}</span></div>)}</div>{!selected.length&&<p className="relative mt-20 text-center font-adventure text-xl font-semibold text-[#15365d]">Choose places to build your campus.</p>}<MapPin className="absolute bottom-4 left-5 text-[#ff8426]"/></div><p className="font-black text-[#125cdb]">{selected.length}/5 locations selected</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{places.map(place=><button type="button" key={place} onClick={()=>toggle(place)} className={`flex items-center justify-between rounded-xl border-2 p-3 text-left font-semibold ${selected.includes(place)?"border-emerald-400 bg-emerald-50 text-emerald-700":"border-[#dce5f2]"}`}>{place}{selected.includes(place)&&<Check size={18}/>}</button>)}</div><Submit disabled={selected.length!==5} label="Build my school" onClick={()=>onAnswer({correct:true,score:100,response:selected})}/></ActivityShell>}
