"use client";
import { useMemo, useState } from "react";
import { ArrowDown, ArrowUp, Clock } from "lucide-react";
import type { ActivityProps } from "@/components/activities/multiple-choice-activity";
import { Submit } from "@/components/activities/multiple-choice-activity";
import { ActivityShell } from "@/components/activities/activity-shell";
import { shuffleOptions } from "@/lib/learning/shuffle";

export function SchoolScheduleActivity({activity,onAnswer,onProgress}:ActivityProps){const initial=useMemo(()=>shuffleOptions(activity.items[0].options??[],activity.id),[activity]);const [order,setOrder]=useState(initial);const [reason,setReason]=useState("");function move(index:number,delta:number){const target=index+delta;if(target<0||target>=order.length)return;const next=[...order];[next[index],next[target]]=[next[target],next[index]];setOrder(next);onProgress?.({order:next,reason})}return <ActivityShell eyebrow="Design the School Day" instructions={activity.instructions}><div className="grid gap-2">{order.map((entry,index)=><div key={entry} className="flex items-center gap-3 rounded-2xl border border-[#dce5f2] bg-white p-3"><span className="grid size-9 place-items-center rounded-xl bg-blue-50 font-black text-[#125cdb]">{index+1}</span><Clock size={18} className="text-[#ff8426]"/><span className="flex-1 font-bold text-[#31445f]">{entry}</span><button type="button" aria-label={`Move ${entry} up`} onClick={()=>move(index,-1)} disabled={index===0} className="rounded-lg p-2 text-[#125cdb] disabled:opacity-25"><ArrowUp size={18}/></button><button type="button" aria-label={`Move ${entry} down`} onClick={()=>move(index,1)} disabled={index===order.length-1} className="rounded-lg p-2 text-[#125cdb] disabled:opacity-25"><ArrowDown size={18}/></button></div>)}</div><label className="label mt-5">Why did you choose this order?<select value={reason} onChange={event=>{setReason(event.target.value);onProgress?.({order,reason:event.target.value})}} className="field mt-2"><option value="">Choose one reason</option>{activity.items[1].options?.map(option=><option key={option}>{option}</option>)}</select></label><Submit disabled={!reason} label="Save my school day" onClick={()=>onAnswer({correct:true,score:100,response:{order,reason}})}/></ActivityShell>}
