"use client";
import { useState } from "react";
import { Award, Sparkles } from "lucide-react";
import type { ActivityProps } from "@/components/activities/multiple-choice-activity";
import { Submit } from "@/components/activities/multiple-choice-activity";
import { ActivityShell } from "@/components/activities/activity-shell";
import { WritingReview } from "@/components/activities/writing-review";
import { analyzeWriting, createWritingRecord, type WritingAnalysis, type WritingIssue } from "@/lib/learning/writing-evaluator";

export function SchoolProfileActivity({activity,onAnswer,onProgress}:ActivityProps){const [profile,setProfile]=useState<Record<string,string>>({});const [analysis,setAnalysis]=useState<WritingAnalysis|null>(null);const [first,setFirst]=useState<Record<string,string>|null>(null);const [history,setHistory]=useState<WritingIssue[]>([]);function update(id:string,value:string){const next={...profile,[id]:value};setProfile(next);setAnalysis(null);onProgress?.(next)}const complete=activity.items.every(item=>(item.options?Boolean(profile[item.id]):(profile[item.id]?.trim().split(/\s+/).length??0)>=3));const writtenItems=activity.items.filter(item=>!item.options);function review(){if(first===null)setFirst({...profile});const results=writtenItems.map(item=>analyzeWriting(profile[item.id]??"",{minWords:3}));const issues=results.flatMap(result=>result.issues);setAnalysis({issues,blockingIssues:issues.filter(issue=>issue.blocking),suggestions:issues.filter(issue=>!issue.blocking),canComplete:results.every(result=>result.canComplete),wordCount:results.reduce((sum,result)=>sum+result.wordCount,0),sentenceCount:results.reduce((sum,result)=>sum+result.sentenceCount,0)});setHistory(current=>[...current,...issues])}function save(){onAnswer({correct:true,score:100,response:createWritingRecord(first??profile,history,profile)})}return <ActivityShell eyebrow="My Perfect School" instructions={activity.instructions}><div className="grid gap-4 sm:grid-cols-2">{activity.items.map(item=><label key={item.id} className="font-bold text-[#31445f]">{item.prompt}{item.options?<select value={profile[item.id]??""} onChange={event=>update(item.id,event.target.value)} className="field mt-2"><option value="">Choose one</option>{item.options.map(option=><option key={option}>{option}</option>)}</select>:<input value={profile[item.id]??""} onChange={event=>update(item.id,event.target.value)} className="field mt-2" placeholder="Write one complete sentence…"/>}</label>)}</div>{complete&&<div className="mt-6 rounded-3xl border border-emerald-200 bg-gradient-to-br from-emerald-50 to-blue-50 p-5 text-center"><Award className="mx-auto text-[#ff8426]"/><p className="mt-2 text-xs font-black uppercase tracking-widest text-emerald-700">School Profile Card</p><h3 className="font-adventure mt-2 text-2xl font-semibold text-[#10233f]">My Perfect School <Sparkles className="inline" size={20}/></h3>{activity.items.map(item=><p key={item.id} className="mt-1 font-semibold text-[#31445f]"><strong>{item.prompt}:</strong> {profile[item.id]}</p>)}</div>}{analysis&&<WritingReview analysis={analysis}/>} {writtenItems.length===0?<Submit disabled={!complete} label="Create school profile" onClick={()=>onAnswer({correct:true,score:100,response:profile})}/>:!analysis?.canComplete?<Submit disabled={!complete} label={analysis?"Review again":"Review my writing"} onClick={review}/>:<Submit disabled={false} label="Create school profile" onClick={save}/>}</ActivityShell>}
