"use client";
import { useState } from "react";
import type { ActivityProps } from "@/components/activities/multiple-choice-activity";
import { Submit } from "@/components/activities/multiple-choice-activity";
import { ActivityShell } from "@/components/activities/activity-shell";
import { WritingReview } from "@/components/activities/writing-review";
import { analyzeWriting, createWritingRecord, type WritingAnalysis, type WritingIssue } from "@/lib/learning/writing-evaluator";

export function WritingActivity({ activity, onAnswer, initialResponse, onProgress }: ActivityProps) {
  const item=activity.items[0]; const initial=typeof initialResponse==="string"?initialResponse:""; const [value,setValue]=useState(initial); const [analysis,setAnalysis]=useState<WritingAnalysis|null>(null); const [firstVersion,setFirstVersion]=useState<string|null>(null); const [history,setHistory]=useState<WritingIssue[]>([]);
  const words=value.trim()?value.trim().split(/\s+/).length:0; const sentences=value.split(/[.!?]+/).filter((sentence)=>sentence.trim().length>0).length; const usesSentenceGoal=Boolean(item.minSentences); const minimum=item.minSentences??0; const maximum=item.maxSentences??Number.POSITIVE_INFINITY; const lengthReady=usesSentenceGoal?sentences>=minimum&&sentences<=maximum:words>=(item.minWords??1);
  function update(next:string){setValue(next);setAnalysis(null);onProgress?.(next)}
  function review(){if(firstVersion===null)setFirstVersion(value);const result=analyzeWriting(value,{minWords:item.minWords,minSentences:item.minSentences,maxSentences:item.maxSentences,requireSecondConditional:item.requireSecondConditional,requiredElements:item.writingRequirements?.map(requirement=>({label:requirement.label,pattern:new RegExp(requirement.pattern,"i"),message:requirement.message}))});setAnalysis(result);setHistory(current=>[...current,...result.issues])}
  function complete(){onAnswer({correct:true,score:100,response:createWritingRecord(firstVersion??value,history,value)})}
  return <ActivityShell eyebrow="Share your story" instructions={activity.instructions}><p className="rounded-2xl bg-orange-50 p-5 text-lg font-semibold leading-8 text-[#66310e]">{item.prompt}</p>{item.sentenceStarters?.length?<div className="mt-5 rounded-2xl border border-orange-200 bg-white p-4"><p className="font-bold text-[#66310e]">Sentence starters</p><div className="mt-2 flex flex-wrap gap-2">{item.sentenceStarters.map((starter)=><span key={starter} className="rounded-full bg-orange-50 px-3 py-1.5 text-sm font-semibold text-[#7c3d0a]">{starter}</span>)}</div></div>:null}<label className="label mt-6" htmlFor="writing-response">Your response</label><textarea id="writing-response" value={value} onChange={(event)=>update(event.target.value)} className="field min-h-44 resize-y py-4" placeholder="Tell your story here…"/><div className="mt-2 flex justify-between gap-4 text-sm font-bold text-[#62708a]"><span>Write → receive feedback → revise → complete.</span><span className={lengthReady?"text-[#21a46b]":sentences>maximum?"text-red-600":""}>{usesSentenceGoal?`${sentences} / ${minimum}–${maximum} sentences`:`${words} / ${item.minWords??1} words`}</span></div>{analysis&&<WritingReview analysis={analysis}/>} {!analysis?.canComplete?<Submit disabled={!lengthReady} label={analysis?"Review again":"Review my writing"} onClick={review}/>:<Submit disabled={false} label="Complete writing activity" onClick={complete}/>}</ActivityShell>;
}
